### ISSUE TITLE
[Dependent on Issue #5, #6, #7] Migrate database

### ISSUE THREAD

**Issue by Kacper3331** [Ragnarson-Internship2016/group-I#10]
Create users, items and wishlists tables.

**Comment by student-tomasz** [comment]
I think this issue is not needed, and should be closed and marked `duplicate` or even `invalid`. We'll migrate the database within a single PR in which any model gets added or updated with new associations. We shouldn't encounter a situation that requires us to explicitly migrate a database.

**Comment by agalkiewicz** [comment]
:+1:
