### ISSUE TITLE
Only logged in user can edit items on his wishlist

### ISSUE THREAD

**Issue by Kacper3331** [Ragnarson-Internship2016/group-I#16]
Set a rule that only logged in user can edit items on his wishlist.

**Comment by kamildebicki** [comment]
+Add Rule - Only Signed in user can edit items on his wishlist
+Add view for editing specific item
+Tests

**Comment by shadrk** [comment]
IMO setting rules should be a part of different issue - what do you think?

**Comment by shadrk** [comment]
-Add Rule - Only Signed in user can delete items from his wishlist(button for delete specific item on whislist)
