### ISSUE TITLE
[Dependent on Issue #21] Set the rule that guest can only see one specific list from the link he's given

### ISSUE THREAD

**Issue by agalkiewicz** [Ragnarson-Internship2016/group-I#22]

**Comment by student-tomasz** [comment]
I don't really see any way we could enforce such rule? The invitation links should be long and random enough that stumbling upon another wishlist should be almost impossible.

So, guest've got the link, guest can see the list. Guest doesn't have a link, guest shouldn't be able to guess the link. Nothing more is required imo.

**Comment by agalkiewicz** [comment]
@student-tomasz: You're right.
