### ISSUE TITLE
[Dependent on Issue #24] Viewing specific wishlist

### ISSUE THREAD

**Issue by agalkiewicz** [Ragnarson-Internship2016/group-I#25]
User is redirected to separate page with more detailed information about wishlist by clicking on one of the lists in the table.

**Comment by kamil506** [comment]
+ Add Rule - Only Signed in user can delete a wishlist
+ Tests

**Comment by kamildebicki** [comment]
+~~Add Rule - Only Signed in user can delete items from his wishlist(button for delete specific item on whislist)~~ (moved to #16) - Shadi
+Add Rule - Only Signed in user can view one of his wishlists
+Tests
