### ISSUE TITLE
[Dependent on Issues #21, #24] Add information about wishlist unique link

### ISSUE THREAD

**Issue by agalkiewicz** [Ragnarson-Internship2016/group-I#29]
When user views information about specific wishlist, can also copy the link to it.

**Comment by kamildebicki** [comment]
~~\+ Set the rule that guest can only see one specific list from the link he's given~~

**Comment by AKorzeniowski** [comment]
@kamil506 How do you think it would be enforced? I thought unique links would solve that, but maybe I misunderstood.

**Comment by shadre** [comment]
^ Yes, this is a wrong place for setting a rule. This should be ensured by authorization.

**Comment by agalkiewicz** [comment]
No, it's completely unnecessary. When you have a link, you can view one specific list indeed. One link - one wishlist.

**Comment by agalkiewicz** [comment]
I think that the purpose of this issue is to create an element in view (in view 'list of wishlists' or 'specific wishlist') which provides copying this unique link - as my description says.

**Comment by shadre** [comment]
Correct. And it should probably be done together with wishlist view. I crossed out @Kacper3331's comment for clarity.

**Comment by shadre** [comment]
I'm doing this issue within #25
