### ISSUE TITLE
Draw views prototypes

### ISSUE THREAD

**Issue by agalkiewicz** [Ragnarson-Internship2016/group-I#30]
- [ ] - root view ('sign up'/'log in' buttons)
- [ ] - logged in view (list of lists, buttons for adding a list and deleting one, button for signing out)
- [ ] - list view (list of items with a checkbox/button allowing the user to choose that item; logged in user gets additional buttons for editing the list)

**Comment by agalkiewicz** [comment]
https://gomockingbird.com/projects/4g8dwly/4gXVnC Ogólny zarys, jak mają wyglądać poszczególne strony i jak przechodzić pomiędzy nimi (w rogach button'ów i innych są hiperłącza). Nie rozmawiajmy na razie o kolorach. Miałam ograniczony wybór. :D Na dole jest przycisk 'pages'. Można bezpośrednio którąś obejrzeć. Sign up już sobie darowałam, bo wiadomo, że będzie podobna do sign in. Gdzieniegdzie są komentarze w dymkach.

**Comment by agalkiewicz** [comment]
https://gomockingbird.com/projects/4g8dwly The mock-up on how particular pages may look like and how user can go through the app (links in elements corners). Don't talk about colours. I had limited choice. :D There is 'pages' button at the bottom - you can choose specific page to view. There are comments in some places.

Personally, I like @Schocker 's ideas on items arrangement and home page look.

**Comment by AKorzeniowski** [comment]
This is how I imagined the index page. I had a variant similar to what @agalkiewicz suggested, i.e. no forms on the page, "Sign up" as CTA and the login button moved somewhere else. But that's up for discussion.
![main page](https://cloud.githubusercontent.com/assets/803232/16955418/ce3cf3a6-4dd4-11e6-9210-51ee51fbb39d.png)

When it comes to list view, I think that every item should be a card and they would get arranged in masonry grid (like on Pinterest, http://masonry.desandro.com/).
![list view-v1](https://cloud.githubusercontent.com/assets/803232/16955412/c82fda1e-4dd4-11e6-98c3-551b520add79.png)

**Comment by student-tomasz** [comment]
@Schocker I like those a lot! Great readability. 👍 for those. I've always loved this masonry grid effect. :) Would prolly work even better with images for gifts, instead of text.

**Comment by shadre** [comment]
For the homepage, I like @agalkiewicz's one more. For the list view @Schocker's really nice.

**Comment by agalkiewicz** [comment]
/
![1--](https://cloud.githubusercontent.com/assets/7493474/16956989/d8be9482-4dda-11e6-97c4-0fde5b05e77f.png)

/sign_up
![2--sign_up](https://cloud.githubusercontent.com/assets/7493474/16957019/f9510040-4dda-11e6-9d5a-8c3b456975b7.png)

/wishlists
![3--wishlists](https://cloud.githubusercontent.com/assets/7493474/16957030/095fabf8-4ddb-11e6-87b7-258fa321d099.png)

/wishlists/new
![4--wishlists-new](https://cloud.githubusercontent.com/assets/7493474/16957048/184af0b4-4ddb-11e6-9034-55a5c62d3a09.png)

/sign_in
![5--sign_in](https://cloud.githubusercontent.com/assets/7493474/16957059/24c4f2c2-4ddb-11e6-9a6e-50ddb008e898.png)

/wishlists/:id
![6--wishlists- id](https://cloud.githubusercontent.com/assets/7493474/16957070/30a6eff0-4ddb-11e6-818b-133d55d3e1f2.png)

view of wishlist for guest
![8-wishlist dla guesta](https://cloud.githubusercontent.com/assets/7493474/16957110/67a758b4-4ddb-11e6-8d5c-17905eb8ac65.png)

/items/new
![7--items-new](https://cloud.githubusercontent.com/assets/7493474/16957083/45a1fe4a-4ddb-11e6-8b4b-7c895351e94e.png)

/items/:id
![9--items- id](https://cloud.githubusercontent.com/assets/7493474/16957087/4e22e750-4ddb-11e6-842e-89f75be81e04.png)

**Comment by student-tomasz** [comment]
- I'd merge views for `/wishlists/new` and `/wishlists/:id` into one view.
- The same goes for `/items/new` and `/items/:id`
- Concept for `/wishlist/:id` requires a big screen to be comfortable to use. Maybe stack it all in a single column. Or design it to be responsive, and stack on demand.
- I like the quick access to the invitation links on `/wishlists` index view.

**Comment by AKorzeniowski** [comment]
![image](https://cloud.githubusercontent.com/assets/803232/17043033/2e60c156-4fb3-11e6-8404-1f4b7bd8f85f.png)
Logged in view (list of lists). 

![list view when logged in alternate 350m](https://cloud.githubusercontent.com/assets/803232/17043045/4c40a8bc-4fb3-11e6-99b0-216778e64e4a.png)
List view when logged in.

![list view when logged in](https://cloud.githubusercontent.com/assets/803232/17043081/97844e8c-4fb3-11e6-98ce-f79de5d480c1.png)
And an alternative version.

I have also done the higher fidelity prototypes of the pages:
![desktop hd](https://cloud.githubusercontent.com/assets/803232/17043122/e9b184cc-4fb3-11e6-8e6c-8cb997ba656a.png)
![image](https://cloud.githubusercontent.com/assets/803232/17043148/2b9351f4-4fb4-11e6-8377-d294f55de0ee.png)
(Still not as much as I wanted)

Currently based on Bootstrap (although I have seen much better ones), we'll see how it goes with views.
